### ISSUE TITLE
Screenshots and Cartesian grid

### ISSUE THREAD

**Issue by mbensing** [JuliaGeodynamics/GeophysicalModelGenerator.jl#17]
Hello,

I wanted to project a map from a published paper on an orthogonal cartesian grid
and used the respective commands of the "Import screenshots" and "Projection" tutorial.
Everything works perfectly fine until the "ProjectCartData" command, for that I get 
a "MethodError" message. Does the projection to an orthogonal cartesian grid of screenshots 
need to be done differently?

Thank you,
Michelle

**Comment by boriskaus** [comment]
How do you call the `ProjectCartData`?  It would be helpful to see the full error message.
In 
```
Data_cart = ProjectCartData(Data_cart, Data, proj)
```
`Data_cart` should be created using `XYZGrid`. Did you do that?

**Comment by mbensing** [comment]
![error](https://user-images.githubusercontent.com/74784010/143323718-a13c06b8-75ae-43ed-83ac-702b0fa7e365.PNG)

**Comment by mbensing** [comment]
Yes, I did that

**Comment by boriskaus** [comment]
That’s indeed the mistake you see in that case.
How do you construct `data_map_Cart_orth`?
Also note that rather than copy-pasting an image here it is better if you copy the code. You can format that nicely in github by putting three back ticks (```) at the beginning and end of the Julia code:
```
My code
```

**Comment by mbensing** [comment]
```cd("D:\\Uni\\Project\\SlabTemplates\\top");

Corner_LowerLeft	= (12.5, 36.5, 5);
Corner_UpperRight       = (19, 41, 5);
Corner_LowerRight	= (19, 36.5, 5);
Corner_UpperLeft	= (12.5, 41, 5);

using GeophysicalModelGenerator

data_map = Screenshot_To_GeoData("Calo2012_top.png", Corner_LowerLeft, Corner_UpperRight, Corner_LowerRight=Corner_LowerRight,Corner_UpperLeft=Corner_UpperLeft)

proj=ProjectionPoint(Lon=13.35, Lat=37.25)
Convert2UTMzone(data_map,proj)
d_Cart = Convert2CartData(data_map,proj)
d_Cart_orth  = CartData(XYZGrid(-20:20:500,-20:20:420,5))
d_Cart_orth  = ProjectCartData(d_Cart_orth, data_map, proj)```

**Comment by mbensing** [comment]
Thank you for the hint!

**Comment by boriskaus** [comment]
This is indeed a bug; it'll take a bit of time for me to fix it as I'm rather busy these days

**Comment by mbensing** [comment]
Okay!

**Comment by boriskaus** [comment]
Thinking more about this: 
Screenshots are only ever needed to visually compare them with other data sets; they are not intended to directly be used in creating model setup as we only have information about the color of every pixel (but not the quantitative values, which would require a colorbar to map this; in many cases there are lines and other attributes on the figure which would make such color translation very difficult). As such, I don't think you would actually need `d_Cart_orth`. Instead, `d_Cart` should be sufficient. `d_Cart` is not perfectly orthogonal, but can be visualised in Paraview just fine with the other data.
 
Or is there a particular reason you want to have `d_Cart_orth`, rather than `d_Cart`?

**Comment by mbensing** [comment]
Yes, that's what I did! I visualised '''d_Cart''' because '''d_Cart_orth''' didn't work and it's only a little distorted on the edges. I just wanted everything to be orthogonal and that slight difference bothered me a little. But it's actually not a big problem. 
Okay good, I will stick to '''d_Cart'''!
