### ISSUE TITLE
Basic tutorial

### ISSUE THREAD

**Issue by mthielma** [JuliaGeodynamics/GeophysicalModelGenerator.jl#93]
When running the Basic Tutorial, I get an error when I try to load the data from Zenodo:

```julia
Tomo_Alps_full = load_GMG("https://zenodo.org/records/10738510/files/Paffrath_2021_SE_Pwave.jld2?download=1")
```

```julia
┌ Warning: type JLD2.SerializedDict does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/IsVcY/src/data/reconstructing_datatypes.jl:605
ERROR: MethodError: Cannot `convert` an object of type JLD2.ReconstructedMutable{:SerializedDict, (:kvvec,), Tuple{Any}} to an object of type Dict{String, String}
```

To me, this seems to be rather JLD2 related, but as it occurs in the first line of the basic tutorial, I thought it'd be good to see why this happens. Anybody else had that issue?

**Comment by boriskaus** [comment]
I agree that this should work as it is very discouraging otherwise.

This works fine for me:
```Julia
julia> using GeophysicalModelGenerator
julia> Tomo_Alps_full = load_GMG("https://zenodo.org/records/10738510/files/Paffrath_2021_SE_Pwave.jld2?download=1")
GeoData 
  size      : (162, 130, 42)
  lon       ϵ [ -13.3019 : 35.3019]
  lat       ϵ [ 30.7638 : 61.2362]
  depth     ϵ [ -606.0385 : 31.0385]
  fields    : (:dVp_Percentage,)
  ```
  
Few things we can try to do:
1) Add some of the key tutorials to the CI (for example the ones that go into the JOSS paper)
2) We often have related failures in the CI system because there are issues with downloading data (happens a lot with `ImportTopo` and sometimes with `load_GMG`. We could perhaps add an automatic retrial and try again another few times to see if that is the issue
3) Is it an issue with your internet speed?

**Comment by albert-de-montserrat** [comment]
It works for me as well. Perhaps using an old JLD2 version? I'm on 0.4.46

**Comment by mthielma** [comment]
I had used v0.4.45 for that. I did an update and now it worked. It does seems weird though as I would not thinkf that these two version should differ by that much. It could be related to downloading data. However, internet speed should not be that bad I think. In any case, it works now. I'll see if it fails again when retrying and reopen the issue if necessary.

**Comment by boriskaus** [comment]
Note the PR #94 does several download attempts which seem to have largely resolved the issue with CI/CD
